#!/usr/bin/env bash
# Build per-vendor INDEX.md catalog files under dist/<Vendor>/.
#
# Each INDEX.md is a markdown table with one row per usable PNG path.
# Description + tags come from a per-vendor lookup TSV at
# scripts/fixtures/icon-index-tags-<vendor>.tsv (filename stem → row,
# category/suffix prefix fallback, heuristic last). Edit the TSV, then
# re-run this script; the INDEX is regenerated deterministically.
#
# Usage:
#   bash scripts/build_icon_index.sh           # both vendors
#   bash scripts/build_icon_index.sh azure
#   bash scripts/build_icon_index.sh fabric

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=scripts/_lib_icon_build.sh
. "${SCRIPT_DIR}/_lib_icon_build.sh"
set_locale_deterministic

FIXTURES_DIR="${SCRIPT_DIR}/fixtures"
AZURE_TSV="${FIXTURES_DIR}/icon-index-tags-azure.tsv"
FABRIC_TSV="${FIXTURES_DIR}/icon-index-tags-fabric.tsv"

# lookup <tsv_file> <key>
#   Prints "<name><TAB><description><TAB><tags>" if a row exists for the
#   key, or empty if not. The TSV columns are key\tname\tdescription\ttags.
#   A literal "-" in name or description means "fall back to heuristic"
#   (lets a row override only the tags column).
lookup() {
  local tsv="$1"
  local key="$2"
  [ -f "${tsv}" ] || return 0
  awk -F'\t' -v k="${key}" '$1 == k { print $2 "\t" $3 "\t" $4; exit }' "${tsv}"
}

# azure_humanize <PascalCaseStem>
#   AzureVirtualMachine → "Azure Virtual Machine"; AzureSQLServer → "Azure SQL Server".
#   The final sed pass uppercases known short acronyms that upstream filenames
#   spell mixed-case (e.g. AzureCosmosDb → "Cosmos Db" → "Cosmos DB"). Extend
#   the list as new vendors land if they introduce new ones.
azure_humanize() {
  printf '%s\n' "$1" \
    | sed -E 's/([a-z])([A-Z])/\1 \2/g; s/([A-Z])([A-Z][a-z])/\1 \2/g' \
    | sed -E 's/\bDb\b/DB/g; s/\bAi\b/AI/g; s/\bMl\b/ML/g; s/\bVm\b/VM/g; s/\bIot\b/IoT/g; s/\bApi\b/API/g; s/\bDns\b/DNS/g; s/\bCdn\b/CDN/g; s/\bWaf\b/WAF/g' \
    | sed -E 's/\bIo T\b/IoT/g; s/\bMy SQL\b/MySQL/g; s/\bPostgre SQL\b/PostgreSQL/g; s/\bMaria DB\b/MariaDB/g; s/\bSignal R\b/SignalR/g; s/\bHD Insight\b/HDInsight/g'
}

# fabric_humanize <snake_case_stem>
#   lakehouse → "Lakehouse"; power_bi → "Power Bi" (override via TSV to "Power BI").
fabric_humanize() {
  printf '%s\n' "$1" | tr '_' ' ' | awk '{ for(i=1;i<=NF;i++) $i = toupper(substr($i,1,1)) substr($i,2); print }'
}

build_azure_index() {
  local dist_root="${REPO_ROOT}/dist/Azure"
  local out="${dist_root}/INDEX.md"

  {
    cat <<'EOF'
# Azure icon index

Generated by `scripts/build_icon_index.sh`. Do not edit by hand — edit
`scripts/fixtures/icon-index-tags-azure.tsv` and regenerate.

Each row points at a usable PNG path. Colored and monochrome `(m)` variants
ship as separate rows so the agent can copy the exact URL needed.

Find an icon by name, category, or tag:

```bash
grep -i 'kubernetes' dist/Azure/INDEX.md      # by name
grep -F '`compute`' dist/Azure/INDEX.md       # by tag
```

EOF
    echo "| path | name | category | variant | description | tags |"
    echo "|------|------|----------|---------|-------------|------|"

    find "${dist_root}" -mindepth 2 -name '*.png' -type f | sort | while IFS= read -r png; do
      local rel category fname stem variant
      rel="${png#${REPO_ROOT}/}"
      category="$(basename "$(dirname "${png}")")"
      fname="$(basename "${png}" .png)"
      if [[ "${fname}" == *'(m)' ]]; then
        stem="${fname%(m)}"
        variant="monochrome"
      else
        stem="${fname}"
        variant="colored"
      fi

      # Lookup precedence (each column independently, "-" means heuristic):
      #   1. Per-stem row (any of name/description/tags can override).
      #   2. tags fall back to cat:<Category> row's tags if no per-stem tags.
      #   3. Final fallback: heuristic name + description, lowercase-category tags.
      local row name description tags cat_row n d t
      name=""
      description=""
      tags=""
      row="$(lookup "${AZURE_TSV}" "${stem}")"
      if [ -n "${row}" ]; then
        IFS=$'\t' read -r n d t <<< "${row}"
        [ -n "${n}" ] && [ "${n}" != "-" ] && name="${n}"
        [ -n "${d}" ] && [ "${d}" != "-" ] && description="${d}"
        [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
      fi
      if [ -z "${tags}" ]; then
        cat_row="$(lookup "${AZURE_TSV}" "cat:${category}")"
        if [ -n "${cat_row}" ]; then
          IFS=$'\t' read -r _ _ t <<< "${cat_row}"
          [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
        fi
      fi
      [ -z "${name}" ] && name="$(azure_humanize "${stem}")"
      [ -z "${description}" ] && description="Microsoft Azure $(azure_humanize "${stem}" | sed -E 's/^Azure ?//')"
      [ -z "${tags}" ] && tags="\`$(echo "${category}" | tr '[:upper:]' '[:lower:]')\`"

      printf '| `%s` | %s | %s | %s | %s | %s |\n' \
        "${rel}" "${name}" "${category}" "${variant}" "${description}" "${tags}"
    done
  } > "${out}"

  local count
  count=$(find "${dist_root}" -mindepth 2 -name '*.png' -type f | wc -l)
  echo "Azure: ${count} rows → ${out#${REPO_ROOT}/}"
}

build_fabric_index() {
  local dist_root="${REPO_ROOT}/dist/Fabric"
  local out="${dist_root}/INDEX.md"

  {
    cat <<'EOF'
# Fabric icon index

Generated by `scripts/build_icon_index.sh`. Do not edit by hand — edit
`scripts/fixtures/icon-index-tags-fabric.tsv` and regenerate.

Each row points at a usable PNG path. Microsoft Fabric ships icons in
multiple sizes (24/28/32/40/48) and suffix families: `_item` (per-artifact),
`_non-item` (workspace + action verbs), `_color` (workload brand), plain
(no suffix).

Find an icon by name or tag:

```bash
grep -i 'lakehouse' dist/Fabric/INDEX.md
grep -F '`pipeline`' dist/Fabric/INDEX.md
```

EOF
    echo "| path | name | size | suffix | description | tags |"
    echo "|------|------|------|--------|-------------|------|"

    find "${dist_root}/png" -name '*.png' -type f | sort | while IFS= read -r png; do
      local rel fname stem size suffix
      rel="${png#${REPO_ROOT}/}"
      fname="$(basename "${png}" .png)"
      if [[ "${fname}" =~ ^(.+)_([0-9]+)_([^_]+)$ ]]; then
        stem="${BASH_REMATCH[1]}"
        size="${BASH_REMATCH[2]}"
        suffix="${BASH_REMATCH[3]}"
      elif [[ "${fname}" =~ ^(.+)_([0-9]+)$ ]]; then
        stem="${BASH_REMATCH[1]}"
        size="${BASH_REMATCH[2]}"
        suffix="plain"
      else
        echo "WARN: unrecognized Fabric filename: ${fname}" >&2
        continue
      fi

      # Lookup precedence (each column independently, "-" means heuristic):
      #   1. Per-stem row (any of name/description/tags can override).
      #   2. tags fall back to suffix:<suffix> row's tags if no per-stem tags.
      #   3. Final fallback: heuristic name + description, fabric+suffix tags.
      local row name description tags suffix_row n d t
      name=""
      description=""
      tags=""
      row="$(lookup "${FABRIC_TSV}" "${stem}")"
      if [ -n "${row}" ]; then
        IFS=$'\t' read -r n d t <<< "${row}"
        [ -n "${n}" ] && [ "${n}" != "-" ] && name="${n}"
        [ -n "${d}" ] && [ "${d}" != "-" ] && description="${d}"
        [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
      fi
      if [ -z "${tags}" ]; then
        suffix_row="$(lookup "${FABRIC_TSV}" "suffix:${suffix}")"
        if [ -n "${suffix_row}" ]; then
          IFS=$'\t' read -r _ _ t <<< "${suffix_row}"
          [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
        fi
      fi
      [ -z "${name}" ] && name="$(fabric_humanize "${stem}")"
      [ -z "${description}" ] && description="Microsoft Fabric $(fabric_humanize "${stem}")"
      [ -z "${tags}" ] && tags="\`fabric\`, \`${suffix}\`"

      printf '| `%s` | %s | %s | %s | %s | %s |\n' \
        "${rel}" "${name}" "${size}" "${suffix}" "${description}" "${tags}"
    done
  } > "${out}"

  local count
  count=$(find "${dist_root}/png" -name '*.png' -type f | wc -l)
  echo "Fabric: ${count} rows → ${out#${REPO_ROOT}/}"
}

mode="${1:-all}"
case "${mode}" in
  azure)        build_azure_index ;;
  fabric)       build_fabric_index ;;
  all|"")       build_azure_index; build_fabric_index ;;
  -h|--help)    echo "usage: $0 [azure|fabric|all]"; exit 0 ;;
  *)            echo "usage: $0 [azure|fabric|all]" >&2; exit 2 ;;
esac
