#!/usr/bin/env bash
# Build per-vendor INDEX.md catalog files under dist/<Vendor>/.
#
# Each INDEX.md is a markdown table with one row per usable PNG path.
# Description + tags come from a per-vendor lookup TSV at
# scripts/fixtures/icon-index-tags-<vendor>.tsv (filename stem → row,
# category/suffix prefix fallback, heuristic last). Edit the TSV, then
# re-run this script; the INDEX is regenerated deterministically.
#
# Usage:
#   bash scripts/build_icon_index.sh           # both vendors
#   bash scripts/build_icon_index.sh azure
#   bash scripts/build_icon_index.sh fabric

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=scripts/_lib_icon_build.sh
. "${SCRIPT_DIR}/_lib_icon_build.sh"
set_locale_deterministic

FIXTURES_DIR="${SCRIPT_DIR}/fixtures"
AZURE_TSV="${FIXTURES_DIR}/icon-index-tags-azure.tsv"
FABRIC_TSV="${FIXTURES_DIR}/icon-index-tags-fabric.tsv"
KUBERNETES_TSV="${FIXTURES_DIR}/icon-index-tags-kubernetes.tsv"
FLUENTUI_TSV="${FIXTURES_DIR}/icon-index-tags-fluentui.tsv"
DEVICON_TSV="${FIXTURES_DIR}/icon-index-tags-devicon.tsv"

# lookup <tsv_file> <key>
#   Prints "<name><TAB><description><TAB><tags>" if a row exists for the
#   key, or empty if not. The TSV columns are key\tname\tdescription\ttags.
#   A literal "-" in name or description means "fall back to heuristic"
#   (lets a row override only the tags column).
lookup() {
  local tsv="$1"
  local key="$2"
  [ -f "${tsv}" ] || return 0
  awk -F'\t' -v k="${key}" '$1 == k { print $2 "\t" $3 "\t" $4; exit }' "${tsv}"
}

# lookup_devicon <tsv_file> <key>
#   Like lookup() but Devicon TSVs have 5 columns: key\tname\tcategory\tdescription\ttags.
#   Prints "<name><TAB><category><TAB><description><TAB><tags>" if a row exists, or empty.
#   A literal "-" in any column means "fall back to heuristic".
lookup_devicon() {
  local tsv="$1"
  local key="$2"
  [ -f "${tsv}" ] || return 0
  awk -F'\t' -v k="${key}" '$1 == k { print $2 "\t" $3 "\t" $4 "\t" $5; exit }' "${tsv}"
}

ACRONYMS_AZURE_TSV="${FIXTURES_DIR}/acronyms-azure.tsv"

# apply_acronyms <tsv> — read stdin, apply each `<pattern><TAB><replacement>` row
# from the TSV in order as `sed -E 's/\b<pattern>\b/<replacement>/g'`. Order in
# the file matters (single-token acronym fixes precede multi-token re-joins).
# Extracted from azure_humanize so AWS/GCP (Phase 3) can supply their own TSV.
apply_acronyms() {
  local tsv="$1" expr="" pat rep
  while IFS=$'\t' read -r pat rep; do
    case "${pat}" in ''|\#*) continue ;; esac
    [ -n "${rep}" ] || continue
    expr="${expr}s/\\b${pat}\\b/${rep}/g;"
  done < "${tsv}"
  if [ -n "${expr}" ]; then sed -E "${expr}"; else cat; fi
}

# azure_humanize <PascalCaseStem>
#   AzureVirtualMachine → "Azure Virtual Machine"; AzureSQLServer → "Azure SQL Server".
#   PascalCase split, then the acronym whitelist in scripts/fixtures/acronyms-azure.tsv
#   uppercases/re-joins known mixed-case acronyms (e.g. "Cosmos Db" → "Cosmos DB").
#   Edit the TSV (not this function) to extend the list.
azure_humanize() {
  printf '%s\n' "$1" \
    | sed -E 's/([a-z])([A-Z])/\1 \2/g; s/([A-Z])([A-Z][a-z])/\1 \2/g' \
    | apply_acronyms "${ACRONYMS_AZURE_TSV}"
}

# fabric_humanize <snake_case_stem>
#   lakehouse → "Lakehouse"; power_bi → "Power Bi" (override via TSV to "Power BI").
fabric_humanize() {
  printf '%s\n' "$1" | tr '_' ' ' | awk '{ for(i=1;i<=NF;i++) $i = toupper(substr($i,1,1)) substr($i,2); print }'
}

build_azure_index() {
  local dist_root="${REPO_ROOT}/dist/Azure"
  local out="${dist_root}/INDEX.md"

  {
    cat <<'EOF'
# Azure icon index

Generated by `scripts/build_icon_index.sh`. Do not edit by hand — edit
`scripts/fixtures/icon-index-tags-azure.tsv` and regenerate.

Each row points at a usable PNG path. Colored and monochrome `(m)` variants
ship as separate rows so the agent can copy the exact URL needed.

Find an icon by name, category, or tag:

```bash
grep -i 'kubernetes' dist/Azure/INDEX.md      # by name
grep -F '`compute`' dist/Azure/INDEX.md       # by tag
```

EOF
    echo "| path | name | category | variant | description | tags |"
    echo "|------|------|----------|---------|-------------|------|"

    find "${dist_root}" -mindepth 2 -name '*.png' -type f | sort | while IFS= read -r png; do
      local rel category fname stem variant
      rel="${png#${REPO_ROOT}/}"
      category="$(basename "$(dirname "${png}")")"
      fname="$(basename "${png}" .png)"
      if [[ "${fname}" == *'(m)' ]]; then
        stem="${fname%(m)}"
        variant="monochrome"
      else
        stem="${fname}"
        variant="colored"
      fi

      # Lookup precedence (each column independently, "-" means heuristic):
      #   1. Per-stem row (any of name/description/tags can override).
      #   2. tags fall back to cat:<Category> row's tags if no per-stem tags.
      #   3. Final fallback: heuristic name + description, lowercase-category tags.
      local row name description tags cat_row n d t
      name=""
      description=""
      tags=""
      row="$(lookup "${AZURE_TSV}" "${stem}")"
      if [ -n "${row}" ]; then
        IFS=$'\t' read -r n d t <<< "${row}"
        [ -n "${n}" ] && [ "${n}" != "-" ] && name="${n}"
        [ -n "${d}" ] && [ "${d}" != "-" ] && description="${d}"
        [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
      fi
      if [ -z "${tags}" ]; then
        cat_row="$(lookup "${AZURE_TSV}" "cat:${category}")"
        if [ -n "${cat_row}" ]; then
          IFS=$'\t' read -r _ _ t <<< "${cat_row}"
          [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
        fi
      fi
      [ -z "${name}" ] && name="$(azure_humanize "${stem}")"
      [ -z "${description}" ] && description="Microsoft Azure $(azure_humanize "${stem}" | sed -E 's/^Azure ?//')"
      [ -z "${tags}" ] && tags="\`$(echo "${category}" | tr '[:upper:]' '[:lower:]')\`"

      printf '| `%s` | %s | %s | %s | %s | %s |\n' \
        "${rel}" "${name}" "${category}" "${variant}" "${description}" "${tags}"
    done
  } > "${out}"

  local count
  count=$(find "${dist_root}" -mindepth 2 -name '*.png' -type f | wc -l)
  echo "Azure: ${count} rows → ${out#${REPO_ROOT}/}"
}

build_fabric_index() {
  local dist_root="${REPO_ROOT}/dist/Fabric"
  local out="${dist_root}/INDEX.md"

  {
    cat <<'EOF'
# Fabric icon index

Generated by `scripts/build_icon_index.sh`. Do not edit by hand — edit
`scripts/fixtures/icon-index-tags-fabric.tsv` and regenerate.

Each row points at a usable PNG path. Microsoft Fabric ships icons in
multiple sizes (24/28/32/40/48) and suffix families: `_item` (per-artifact),
`_non-item` (workspace + action verbs), `_color` (workload brand), plain
(no suffix).

Find an icon by name or tag:

```bash
grep -i 'lakehouse' dist/Fabric/INDEX.md
grep -F '`pipeline`' dist/Fabric/INDEX.md
```

EOF
    echo "| path | name | size | suffix | description | tags |"
    echo "|------|------|------|--------|-------------|------|"

    find "${dist_root}/png" -name '*.png' -type f | sort | while IFS= read -r png; do
      local rel fname stem size suffix
      rel="${png#${REPO_ROOT}/}"
      fname="$(basename "${png}" .png)"
      if [[ "${fname}" =~ ^(.+)_([0-9]+)_([^_]+)$ ]]; then
        stem="${BASH_REMATCH[1]}"
        size="${BASH_REMATCH[2]}"
        suffix="${BASH_REMATCH[3]}"
      elif [[ "${fname}" =~ ^(.+)_([0-9]+)$ ]]; then
        stem="${BASH_REMATCH[1]}"
        size="${BASH_REMATCH[2]}"
        suffix="plain"
      else
        echo "WARN: unrecognized Fabric filename: ${fname}" >&2
        continue
      fi

      # Lookup precedence (each column independently, "-" means heuristic):
      #   1. Per-stem row (any of name/description/tags can override).
      #   2. tags fall back to suffix:<suffix> row's tags if no per-stem tags.
      #   3. Final fallback: heuristic name + description, fabric+suffix tags.
      local row name description tags suffix_row n d t
      name=""
      description=""
      tags=""
      row="$(lookup "${FABRIC_TSV}" "${stem}")"
      if [ -n "${row}" ]; then
        IFS=$'\t' read -r n d t <<< "${row}"
        [ -n "${n}" ] && [ "${n}" != "-" ] && name="${n}"
        [ -n "${d}" ] && [ "${d}" != "-" ] && description="${d}"
        [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
      fi
      if [ -z "${tags}" ]; then
        suffix_row="$(lookup "${FABRIC_TSV}" "suffix:${suffix}")"
        if [ -n "${suffix_row}" ]; then
          IFS=$'\t' read -r _ _ t <<< "${suffix_row}"
          [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
        fi
      fi
      [ -z "${name}" ] && name="$(fabric_humanize "${stem}")"
      [ -z "${description}" ] && description="Microsoft Fabric $(fabric_humanize "${stem}")"
      [ -z "${tags}" ] && tags="\`fabric\`, \`${suffix}\`"

      printf '| `%s` | %s | %s | %s | %s | %s |\n' \
        "${rel}" "${name}" "${size}" "${suffix}" "${description}" "${tags}"
    done
  } > "${out}"

  local count
  count=$(find "${dist_root}/png" -name '*.png' -type f | wc -l)
  echo "Fabric: ${count} rows → ${out#${REPO_ROOT}/}"
}

build_kubernetes_index() {
  local dist_root="${REPO_ROOT}/dist/Kubernetes"
  local out="${dist_root}/INDEX.md"

  {
    cat <<'EOF'
# Kubernetes icon index

Generated by `scripts/build_icon_index.sh`. Do not edit by hand — edit
`scripts/fixtures/icon-index-tags-kubernetes.tsv` and regenerate.

Each row points at a usable PNG path. The Kubernetes icon set ships
two stylistic variants (labeled vs unlabeled) across resources,
control-plane components, and infrastructure components — at 128px
and 256px sizes.

Find an icon by name, variant, or tag:

```bash
grep -i 'pod' dist/Kubernetes/INDEX.md          # by name
grep -F '`network`' dist/Kubernetes/INDEX.md    # by tag
grep -F '| labeled |' dist/Kubernetes/INDEX.md  # by variant
```

EOF
    echo "| path | name | variant | size | description | tags |"
    echo "|------|------|---------|------|-------------|------|"

    find "${dist_root}/png" -name '*.png' -type f | sort | while IFS= read -r png; do
      local rel fname stem size variant subdir
      rel="${png#${REPO_ROOT}/}"
      fname="$(basename "${png}" .png)"
      # Derive subdir family. Path looks like dist/Kubernetes/png/<family>/<labeled|unlabeled>/<file>.png
      subdir="$(dirname "${rel#dist/Kubernetes/png/}")"
      case "${subdir}" in
        resources/labeled)                 variant="labeled" ;;
        resources/unlabeled)               variant="unlabeled" ;;
        control_plane_components/labeled)  variant="control-plane-labeled" ;;
        control_plane_components/unlabeled) variant="control-plane-unlabeled" ;;
        infrastructure_components/labeled) variant="infra-labeled" ;;
        infrastructure_components/unlabeled) variant="infra-unlabeled" ;;
        *)                                 variant="${subdir}" ;;
      esac
      # Stem + size: filename is `<stem>-<size>.png` where stem may contain dashes.
      if [[ "${fname}" =~ ^(.+)-([0-9]+)$ ]]; then
        stem="${BASH_REMATCH[1]}"
        size="${BASH_REMATCH[2]}"
      else
        echo "WARN: unrecognized Kubernetes filename: ${fname}" >&2
        continue
      fi

      # Lookup precedence (each column independently, "-" means heuristic):
      #   1. Per-stem row (any of name/description/tags can override).
      #   2. Final fallback: heuristic name (stem as-is, uppercased first char),
      #      description ("Kubernetes <stem>"), tags ("`kubernetes`, `<variant>`").
      local row name description tags n d t
      name=""
      description=""
      tags=""
      row="$(lookup "${KUBERNETES_TSV}" "${stem}")"
      if [ -n "${row}" ]; then
        IFS=$'\t' read -r n d t <<< "${row}"
        [ -n "${n}" ] && [ "${n}" != "-" ] && name="${n}"
        [ -n "${d}" ] && [ "${d}" != "-" ] && description="${d}"
        [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
      fi
      [ -z "${name}" ] && name="$(printf '%s' "${stem}" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
      [ -z "${description}" ] && description="Kubernetes ${name}"
      [ -z "${tags}" ] && tags="\`kubernetes\`, \`${variant}\`"

      printf '| `%s` | %s | %s | %s | %s | %s |\n' \
        "${rel}" "${name}" "${variant}" "${size}" "${description}" "${tags}"
    done
  } > "${out}"

  local count
  count=$(find "${dist_root}/png" -name '*.png' -type f | wc -l)
  echo "Kubernetes: ${count} rows → ${out#${REPO_ROOT}/}"
}

build_fluentui_index() {
  local dist_root="${REPO_ROOT}/dist/FluentUI"
  local out="${dist_root}/INDEX.md"

  {
    cat <<'EOF'
# FluentUI icon index

Generated by `scripts/build_icon_index.sh`. Do not edit by hand — edit
`scripts/fixtures/icon-index-tags-fluentui.tsv` and regenerate.

Each row points at a usable PNG path. The FluentUI System Icons set
ships a curated subset of 25 architecture-diagram concepts at sizes
24px / 32px / 48px in the `_color` (filled-color) variant. Scope is
defined by `scripts/fixtures/fluentui-curation.txt`.

Find an icon by name, size, or tag:

```bash
grep -i 'cloud' dist/FluentUI/INDEX.md         # by name
grep -F '`security`' dist/FluentUI/INDEX.md    # by tag
grep -F '| 48 |' dist/FluentUI/INDEX.md        # by size
```

EOF
    echo "| path | name | size | description | tags |"
    echo "|------|------|------|-------------|------|"

    find "${dist_root}/png" -name '*.png' -type f | sort | while IFS= read -r png; do
      local rel fname stem size
      rel="${png#${REPO_ROOT}/}"
      fname="$(basename "${png}" .png)"
      # Filename pattern: <stem>_<size>_color.png — stem may contain underscores.
      if [[ "${fname}" =~ ^(.+)_([0-9]+)_color$ ]]; then
        stem="${BASH_REMATCH[1]}"
        size="${BASH_REMATCH[2]}"
      else
        echo "WARN: unrecognized FluentUI filename: ${fname}" >&2
        continue
      fi

      local row name description tags n d t
      name=""
      description=""
      tags=""
      row="$(lookup "${FLUENTUI_TSV}" "${stem}")"
      if [ -n "${row}" ]; then
        IFS=$'\t' read -r n d t <<< "${row}"
        [ -n "${n}" ] && [ "${n}" != "-" ] && name="${n}"
        [ -n "${d}" ] && [ "${d}" != "-" ] && description="${d}"
        [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
      fi
      # Heuristic fallback for unknown stem: convert snake_case to Title Case.
      [ -z "${name}" ] && name="$(printf '%s' "${stem}" | awk -F'_' '{ for(i=1;i<=NF;i++) $i = toupper(substr($i,1,1)) substr($i,2); OFS=" "; $1=$1; print }')"
      [ -z "${description}" ] && description="FluentUI ${name}"
      [ -z "${tags}" ] && tags="\`fluentui\`"

      printf '| `%s` | %s | %s | %s | %s |\n' \
        "${rel}" "${name}" "${size}" "${description}" "${tags}"
    done
  } > "${out}"

  local count
  count=$(find "${dist_root}/png" -name '*.png' -type f | wc -l)
  echo "FluentUI: ${count} rows → ${out#${REPO_ROOT}/}"
}

build_devicon_index() {
  local dist_root="${REPO_ROOT}/dist/Devicon"
  local out="${dist_root}/INDEX.md"

  {
    cat <<'EOF'
# Devicon icon index

Generated by `scripts/build_icon_index.sh`. Do not edit by hand — edit
`scripts/fixtures/icon-index-tags-devicon.tsv` and regenerate.

Each row points at a usable PNG path. The Devicon set ships a curated
subset of ~150 popular dev-tool concepts at 48px in the `-original`
variant. Scope is defined by `scripts/fixtures/devicon-curation.txt`.

Find an icon by name, category, or tag:

```bash
grep -i 'python' dist/Devicon/INDEX.md          # by name
grep -F '`language`' dist/Devicon/INDEX.md      # by tag
grep -F '| database |' dist/Devicon/INDEX.md    # by category
```

EOF
    echo "| path | name | category | description | tags |"
    echo "|------|------|----------|-------------|------|"

    find "${dist_root}/png" -name '*.png' -type f | sort | while IFS= read -r png; do
      local rel fname stem
      rel="${png#${REPO_ROOT}/}"
      fname="$(basename "${png}" .png)"
      # Filename pattern: <stem>-original_48.png — stem may contain hyphens.
      if [[ "${fname}" =~ ^(.+)-original_48$ ]]; then
        stem="${BASH_REMATCH[1]}"
      else
        echo "WARN: unrecognized Devicon filename: ${fname}" >&2
        continue
      fi

      local row name category description tags n c d t
      name=""
      category=""
      description=""
      tags=""
      row="$(lookup_devicon "${DEVICON_TSV}" "${stem}")"
      if [ -n "${row}" ]; then
        IFS=$'\t' read -r n c d t <<< "${row}"
        [ -n "${n}" ] && [ "${n}" != "-" ] && name="${n}"
        [ -n "${c}" ] && [ "${c}" != "-" ] && category="${c}"
        [ -n "${d}" ] && [ "${d}" != "-" ] && description="${d}"
        [ -n "${t}" ] && [ "${t}" != "-" ] && tags="${t}"
      fi
      # Heuristic fallbacks for unknown stem.
      [ -z "${name}" ] && name="$(printf '%s' "${stem}" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
      [ -z "${category}" ] && category="uncategorized"
      [ -z "${description}" ] && description="Devicon ${name}"
      [ -z "${tags}" ] && tags="\`devicon\`, \`${category}\`"

      printf '| `%s` | %s | %s | %s | %s |\n' \
        "${rel}" "${name}" "${category}" "${description}" "${tags}"
    done
  } > "${out}"

  local count
  count=$(find "${dist_root}/png" -name '*.png' -type f | wc -l)
  echo "Devicon: ${count} rows → ${out#${REPO_ROOT}/}"
}

mode="${1:-all}"
case "${mode}" in
  azure)        build_azure_index ;;
  fabric)       build_fabric_index ;;
  kubernetes)   build_kubernetes_index ;;
  fluentui)     build_fluentui_index ;;
  devicon)      build_devicon_index ;;
  all|"")       build_azure_index; build_fabric_index; build_kubernetes_index; build_fluentui_index; build_devicon_index ;;
  -h|--help)    echo "usage: $0 [azure|fabric|kubernetes|fluentui|devicon|all]"; exit 0 ;;
  *)            echo "usage: $0 [azure|fabric|kubernetes|fluentui|devicon|all]" >&2; exit 2 ;;
esac
