#!/usr/bin/env node
// Experimental: Terraform azurerm -> PlantUML architecture diagram.
//
// Best-effort, regex-based (NOT a full HCL parser). It extracts top-level
//   resource "azurerm_<type>" "<name>" { ... }
// blocks, maps each known type to an Azure icon path via
// scripts/fixtures/iac-azurerm-icon-map.tsv, and emits a .puml whose nodes
// use <img:URL> icons and whose edges are inferred from Terraform references
// (`<type>.<name>` tokens) found inside each block body.
//
// Unknown resource types are NOT dropped: they render as plain text-labelled
// nodes and are reported on stderr as a coverage report.
//
// Usage:   node scripts/iac_to_diagram.mjs <path-to.tf> [--ref <git-ref>]
// Output:  PlantUML on stdout; coverage report on stderr.
//
// Limitations (by design, this phase): no modules / for_each / count /
// interpolation / data sources; single-file; azurerm only. See README.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const RAW_BASE = "https://raw.githubusercontent.com/hanv89/azure-icons-for-architecture-diagrams";

const args = process.argv.slice(2);
const tfPath = args.find((a) => !a.startsWith("--"));
const refIdx = args.indexOf("--ref");

if (!tfPath) {
  console.error("usage: node scripts/iac_to_diagram.mjs <path-to.tf> [--ref <git-ref>]");
  process.exit(2);
}

// --ref is interpolated into the emitted <img:URL>; validate it as a git ref
// so a stray value can't inject markup or a path-traversal fetch target, and
// a missing value can't become the literal string "undefined" in every URL.
// Recommended: pass --ref icons-vX.Y.Z for output pinned to a released snapshot.
let ref = "main";
if (refIdx >= 0) {
  const val = args[refIdx + 1];
  if (!val || val.startsWith("--") || !/^[A-Za-z0-9._/-]+$/.test(val) || val.includes("..")) {
    console.error(`ERROR: --ref must be a git ref matching [A-Za-z0-9._/-]+ with no '..' (got: ${val === undefined ? "<missing>" : JSON.stringify(val)})`);
    process.exit(2);
  }
  ref = val;
}

// --- load the icon map (type -> {path,label}) ---
const map = new Map();
const mapText = readFileSync(join(SCRIPT_DIR, "fixtures", "iac-azurerm-icon-map.tsv"), "utf8");
for (const line of mapText.split("\n")) {
  if (!line.trim() || line.startsWith("#")) continue;
  const [type, path, label] = line.split("\t");
  if (type && path && label) map.set(type.trim(), { path: path.trim(), label: label.trim() });
}

let tfRaw;
try {
  tfRaw = readFileSync(tfPath, "utf8");
} catch (e) {
  console.error(`ERROR: cannot read ${tfPath}: ${e.message}`);
  process.exit(2);
}

// Strip whole-line comments (#... and //...) so a commented-out `resource`
// block is not parsed as a real resource (phantom node). Block comments
// (/* */) and inline trailing comments are left as-is — best-effort; the
// brace-balancer below is string-aware so braces inside string values do not
// desync block slicing. Known limitation: braces inside heredocs (<<EOF) are
// not specially handled (documented in README).
const tf = tfRaw
  .split("\n")
  .filter((l) => !/^\s*(#|\/\/)/.test(l))
  .join("\n");

// --- extract resource blocks (string-aware brace-balanced, best-effort) ---
const resources = []; // {type, name, alias, body}
const re = /resource\s+"(azurerm_[a-z0-9_]+)"\s+"([A-Za-z0-9_-]+)"\s*\{/g;
let m;
while ((m = re.exec(tf)) !== null) {
  const [, type, name] = m;
  // brace-balance from the opening {; ignore braces inside "..." string values
  let depth = 1;
  let inStr = false;
  let i = re.lastIndex;
  for (; i < tf.length && depth > 0; i++) {
    const c = tf[i];
    if (inStr) {
      if (c === "\\") { i++; continue; } // skip escaped char
      if (c === '"') inStr = false;
    } else if (c === '"') {
      inStr = true;
    } else if (c === "{") depth++;
    else if (c === "}") depth--;
  }
  const body = tf.slice(re.lastIndex, i - 1);
  resources.push({ type, name, alias: `${type}__${name}`.replace(/[^A-Za-z0-9_]/g, "_"), body });
  re.lastIndex = i; // resume scanning after this block
}

if (resources.length === 0) {
  console.error("ERROR: no `resource \"azurerm_*\" \"name\"` blocks found");
  process.exit(1);
}

// --- build alias lookup for edge inference ---
const byRef = new Map(); // "<type>.<name>" -> alias
for (const r of resources) byRef.set(`${r.type}.${r.name}`, r.alias);

// --- emit nodes ---
const lines = [];
lines.push("@startuml IaCDiagram");
lines.push("' Generated by scripts/iac_to_diagram.mjs (experimental) from " + tfPath);
lines.push("top to bottom direction");
lines.push("skinparam linetype ortho");
lines.push("skinparam shadowing false");
lines.push("skinparam rectangle {");
lines.push("  BackgroundColor transparent");
lines.push("  BorderColor #888888");
lines.push("  FontColor #1F2937");
lines.push("}");
lines.push("");

const uncovered = new Map(); // type -> count
for (const r of resources) {
  const hit = map.get(r.type);
  if (hit) {
    const url = `${RAW_BASE}/${ref}/${hit.path}`;
    lines.push(`rectangle "<img:${url}>\\n${hit.label}: ${r.name}" as ${r.alias}`);
  } else {
    uncovered.set(r.type, (uncovered.get(r.type) || 0) + 1);
    lines.push(`rectangle "${r.type}: ${r.name}" as ${r.alias}`);
  }
}
lines.push("");

// --- emit edges from references inside each block body ---
const edges = new Set();
const refTok = /\b(azurerm_[a-z0-9_]+)\.([A-Za-z0-9_-]+)\b/g;
for (const r of resources) {
  let t;
  while ((t = refTok.exec(r.body)) !== null) {
    const target = byRef.get(`${t[1]}.${t[2]}`);
    if (target && target !== r.alias) edges.add(`${r.alias} --> ${target}`);
  }
}
for (const e of [...edges].sort()) lines.push(e);

lines.push("");
lines.push("@enduml");
process.stdout.write(lines.join("\n") + "\n");

// --- coverage report (stderr) ---
const covered = resources.length - [...uncovered.values()].reduce((a, b) => a + b, 0);
process.stderr.write(`iac_to_diagram: ${covered}/${resources.length} resource(s) mapped to icons.\n`);
if (uncovered.size > 0) {
  process.stderr.write(`uncovered types (rendered as text-labelled nodes, not dropped):\n`);
  for (const [t, n] of [...uncovered.entries()].sort()) {
    process.stderr.write(`  - ${t} (x${n})\n`);
  }
}
