#!/usr/bin/env bash
# Assert every per-vendor INDEX.md is internally consistent with dist/:
#   - every `path` row resolves to a real PNG on disk;
#   - the row count reconciles with `find dist/<Vendor> -name '*.png'`.
#
# INDEX.md is generated by build_icon_index.sh; a stale row (pointing at a
# renamed/removed PNG) or a row/file count mismatch means the catalog the
# skill tells agents to grep is lying.
#
# The path lives in the first table column wrapped in backticks:
#   | `dist/<Vendor>/.../<file>.png` | name | ... |
#
# Exit codes:
#   0 — every INDEX row resolves + counts reconcile for all vendors.
#   1 — a stale row or a count mismatch.
#   2 — environment problem (no INDEX.md found).
set -uo pipefail
export LC_ALL=C

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${REPO_ROOT}"

FAILED=0
fail() { FAILED=$(( FAILED + 1 )); echo "FAIL: $*" >&2; }

shopt -s nullglob
INDEXES=(dist/*/INDEX.md)
[ "${#INDEXES[@]}" -ge 1 ] || { echo "ERROR: no dist/*/INDEX.md found" >&2; exit 2; }

for idx in "${INDEXES[@]}"; do
  vendor="$(basename "$(dirname "${idx}")")"

  # Extract the backtick-wrapped path from each table row whose first cell
  # is a `dist/...png` path. Skip the header + separator rows.
  mapfile -t paths < <(
    grep -E '^\|[[:space:]]*`dist/[^`]+\.png`' "${idx}" \
      | sed -E 's/^\|[[:space:]]*`([^`]+)`.*/\1/'
  )

  rows="${#paths[@]}"
  if [ "${rows}" -eq 0 ]; then
    fail "${idx}: no usable path rows parsed (format drift?)"
    continue
  fi

  missing=0
  for p in "${paths[@]}"; do
    [ -f "${p}" ] || { fail "${idx}: row points at missing file: ${p}"; missing=$(( missing + 1 )); }
  done

  # Reconcile row count vs actual PNGs under the vendor dir.
  actual="$(find "dist/${vendor}" -name '*.png' | wc -l | tr -d ' ')"
  if [ "${rows}" -ne "${actual}" ]; then
    fail "${idx}: row count ${rows} != ${actual} PNG file(s) under dist/${vendor}/"
  fi

  if [ "${missing}" -eq 0 ] && [ "${rows}" -eq "${actual}" ]; then
    echo "PASS  ${vendor}: ${rows} INDEX rows all resolve + reconcile with dist/ PNG count."
  fi
done

if [ "${FAILED}" -eq 0 ]; then
  echo "PASS  all ${#INDEXES[@]} vendor INDEX.md files are consistent with dist/."
  exit 0
fi
echo "test_index_integrity: ${FAILED} failure(s)." >&2
exit 1
